jogja_rasa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('restaurant/', include('restaurants.urls')),
    path('review/', include('review.urls')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('reservasi/', include('reservation.urls', namespace='reservation')),
    path('bookmark/', include('bookmarks.urls', namespace='bookmarks')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from .views import register, login, show_landing_page, logout_user, search_restaurants, rekomendasi_makanan, profile, home, add_reservation,show_json, show_json_by_id
from bookmarks import views
app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('cari-resto/', show_landing_page, name='cari-resto'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout_user, name='logout'),
    path('search_restaurants/', search_restaurants, name='search_restaurants'),
    path('get_recommendations/', rekomendasi_makanan, name='get_recommendations'),
    path('profile/', profile, name='profile'),
    path('json/', show_json, name='show_json'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('add_reservation/', add_reservation, name='add_reservation'),
    path('bookmark/', views.bookmark_list, name='bookmark_list'),
    path('toggle_bookmark/', views.toggle_bookmark, name='toggle_bookmark'),
]

review/urls.py
from django.urls import path
from review.views import *

app_name = 'review'

urlpatterns =[
    path('',show_review, name='show_review'),
    path('show_restaurants_json/', show_restaurants_json, name='show_restaurants_json'),
    path('show_reviews_json/', show_reviews_json, name='show_reviews_json'),
    path('create_review/', create_review, name='create_review'),
    path('show_review/<uuid:id>/', show_review_more, name='show_review_more'),
    path('show_reviews_by_restaurant_json/<uuid:id>/', show_reviews_by_restaurant_json, name='show_reviews_by_restaurant_json'),
    path('delete_review/<int:id>/', delete_review, name='delete_review'),
    path('create_review_flutter/', create_review_flutter),
    path('show_reviews_json_flutter/', show_reviews_json_flutter),
    path('show_restaurant_reviews_json_flutter/<uuid:id>/', show_restaurant_reviews_json_flutter),
]

review/models.py
from django.db import models
from django.contrib.auth.models import User
from restaurants.models import Restaurant

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateField(null=True)
    rating = models.IntegerField()
    review = models.CharField(max_length=100)

review/forms.py
from django.forms import ModelForm
from .models import Review

class ReviewRestaurantForm(ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "review"]

review/views.py
from django.shortcuts import render
from restaurants.models import Restaurant
from review.models import Review
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
import datetime
from datetime import datetime
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from main.models import UserProfile
from django.http import HttpResponseRedirect
from django.urls import reverse
import json
@login_required(login_url='/login/')
def show_review(request):
    restaurants = Restaurant.objects.all()
    reviews = Review.objects.all()

    context = {
        'can_view_personalized_info': True,
        'can_manage_bookmarks': True,
        'can_rate_and_review': True,
        'can_manage_reservations': True,
        'can_participate_in_forum': True,
        'can_view_restaurants': True,
        'can_search_nearby': True,
        'can_view_reviews': True,
        'can_view_discussions': True,
        'restaurants': restaurants,
        'review': reviews,
        'restaurants_json': serializers.serialize('json', restaurants)
    }

    return render(request, "review.html", context)


@login_required(login_url='/login/')
def show_review_more(request, id):

    restaurant = Restaurant.objects.get(pk=id)
    reviews = Review.objects.filter(restaurant=restaurant)
    users = UserProfile.objects.all()
    
    context = {
        'user_loggedin': request.user,
        'restaurant': restaurant,
        'reviews': serializers.serialize('json', Review.objects.filter(restaurant=restaurant)),
        'users': serializers.serialize('json', users),
    }
    return render(request, 'choose_restaurant.html', context)

@login_required
def delete_review(request, id):
    review = Review.objects.get(pk = id)
    restaurant_pk = review.restaurant.pk
    if request.user.pk == review.user.pk:
        review.delete()
    return HttpResponseRedirect(reverse('review:show_review_more', args=[restaurant_pk]))

@csrf_exempt
@require_POST
def create_review(request):
    resto_id = request.POST.get('pk_resto')
    resto = Restaurant.objects.get(pk=resto_id)
    user = request.user
    date = datetime.now()
    rating = request.POST.get('rating')
    review = request.POST.get('review')
    new_review = Review(user=user, restaurant=resto, review=review, date=date, rating=rating)
    new_review.save()
    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
@require_POST
def create_review_flutter(request):
    data = json.loads(request.body)
    resto_id = data.get('pk_resto')
    rating = data.get('rating')
    review = data.get('review')
    user = request.user
    date = datetime.now()
    resto = Restaurant.objects.get(pk=resto_id)
        
    new_review = Review(user=user, restaurant=resto, review=review, date=date, rating=rating)
    new_review.save()
    return JsonResponse({
        "status" : True
    }, status=201) 

def show_reviews_json_flutter(request):
    reviews = Review.objects.select_related('user','restaurant')

    data = []
    for review in reviews:
        data.append({
            "pk" : review.id,
            "fields" : {
                "date": review.date,
                "username": review.user.username,
                "user": review.user.id,
                "rating": review.rating,
                "review": review.review,
                "restaurant" : review.restaurant.id
            }
        })
        
    return JsonResponse(data, safe=False)


def show_restaurant_reviews_json_flutter(request, id):
    reviews = Review.objects.select_related('user','restaurant')

    data = []
    for review in reviews:
        if review.restaurant.id == id:
            data.append({
                "pk" : review.id,
                "fields" : {
                "date": review.date,
                "username": review.user.username,
                "user": review.user.id,
                "rating": review.rating,
                "review": review.review,
                "restaurant" : review.restaurant.id
                }
            })
        
    return JsonResponse(data, safe=False)
    

def show_restaurants_json(request):
    restaurants = Restaurant.objects.all()
    return HttpResponse(serializers.serialize('json', restaurants), content_type="application/json")

def show_reviews_json(request):
    data = Review.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def show_reviews_by_restaurant_json(request, id):
    data = Review.objects.filter(restaurant=Restaurant.objects.get(pk=id))
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

review/templates/review.html
{% extends 'base.html' %}
{% load static %}
<!--Prettier-->
{% block title %}Review{% endblock title %} 
{% block content %}
<!--Prettier-->
{% include 'navbar.html' %}
<style>
    table{
        width: 75%;
        table-layout: fixed; 
        border-collapse: collapse;
    }
    th{
        font-size: 20px;
        text-align:left;
    }
    th:nth-child(1), td:nth-child(1) {
        width: 5%;
    }

    th:nth-child(2), td:nth-child(2) {
        width: 45%;
    }

    th:nth-child(3), td:nth-child(3) {
        width: 20%;
    }
    th:nth-child(4), td:nth-child(3) {
        width: 20%;
    }
    th,td{
        padding: 6px;
    }
    td, th {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    tr{
        border-bottom: 1px lightblue solid
    }
    .btn-primary {
    padding: 0.75rem 1.5rem;
    background-color: lightblue;
    color: gray;
    font-weight: 600;
    border-radius: 0.375rem;
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
    transition: all 0.3s ease;
    }

    #restaurant-table {
        width: 100%;
        overflow-x: auto;
    }

</style>
<div id="my-data" 
    data-restaurant="{% url 'review:show_restaurants_json' %}"
    data-review="{% url 'review:show_reviews_json' %}"
    create-review = "{% url 'review:create_review' %}">
</div>

<main>
    <h1 class="text-3xl font-bold my-4 text-center text-navy-800">
        Ulasan dan Rating Restoran
    </h1>
    <p class="col-span-3 italic text-center mb-6 text-gray-500">
        "Tinggalkan ulasan Anda untuk membantu pengunjung lain menemukan pengalaman terbaik dan tingkatkan kualitas layanan kami!"
    </p>
   
    <div id="restaurant-table" class="flex justify-center overflow-scroll">
    </div>

</main>

<script>

    const dataElement = document.getElementById('my-data');

    async function getRestaurant() {
        const restaurants = dataElement.getAttribute('data-restaurant');
        return fetch(restaurants).then((res) => res.json());
    }

    async function getReview(){
        const reviews = dataElement.getAttribute('data-review');
        return fetch(reviews).then((res) => res.json());
    }
    async function refreshPage(){
        document.getElementById("restaurant-table").innerHTML = "";
        const allReview = await getReview();
        const allResto = await getRestaurant();

        let htmlString = ` 
            <table>
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Restoran</th>
                        <th>Rating</th>
                        <th>Pengunjung</th>
                    </tr>
                </thead>
            <tbody>
        `;

        let count=0;

        allResto.forEach(resto => {
            let sumRating = 0;
            let countRating = 0;
            if (allReview.length > 0){
                allReview.forEach(review => {
                if (review.fields.restaurant == resto.pk){
                    countRating++;
                    sumRating += review.fields.rating;
                }
                });
            }
            
            let avgRating = 0;

            if (countRating > 0){
                avgRating += sumRating/countRating;
                avgRating = (Math.round(avgRating * 100) / 100).toFixed(2);
            }

            htmlString += `
                <tr>
                    <td>${++count}</td>
                    <td>${resto.fields.name}</td>
                    <td>${avgRating}</td>
                    <td>${countRating}</td>
                    <td>
                        <a href="/review/show_review/${resto.pk}" id="show_review" >
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000" height="40" width="40" version="1.1" id="XMLID_287_" viewBox="0 0 24 24" xml:space="preserve">
                                <rect width="24" height="24" fill="var(--navy-800)" rx="4" ry="4"/>
                                
                                <g id="next">
                                    <g>
                                        <polygon points="6.8,23.7 5.4,22.3 15.7,12 5.4,1.7 6.8,0.3 18.5,12"/>
                                    </g>
                                </g>
                            </svg>
                        </a>
                    </td>
                </tr>
            `;
        });
        htmlString +=  `</tbody></table>`;
        document.getElementById("restaurant-table").innerHTML = htmlString;
        
    }

    refreshPage();

    
    
</script>
{% include 'footer.html' %}
{% endblock content %}